from functools import partial
import os

root = os.getcwd()
concat = partial(os.path.join, root)
make = partial(os.makedirs, exist_ok=True)

Furry_Avatar_Bases = [
    'Avatars/Furry Bases/Rezillo Ryker Rexonium',
    'Avatars/Furry Bases/Rezillo Ryker Canis Wolf',
    'Avatars/Furry Bases/Rezillo Ryker Cervus Durr',
    'Avatars/Furry Bases/Zoidberg656 Zoichi',
    'Avatars/Furry Bases/Zoidberg656 Pompfu',
    'Avatars/Furry Bases/Zoidberg656 Donedrude',
    'Avatars/Furry Bases/Zoidberg656 Flufi',
    'Avatars/Furry Bases/Zoidberg656 Skellichi',
    'Avatars/Furry Bases/Zoidberg656 College Canine',
    'Avatars/Furry Bases/Zoidberg656 Leo The Wolf',
    'Avatars/Furry Bases/Zoidberg656 Atlas The Cat',
    'Avatars/Furry Bases/Zoidberg656 Sanobu',
    'Avatars/Furry Bases/Zoidberg656 Sanobu V2'
    'Avatars/Furry Bases/Rantis Rantichi',
    'Avatars/Furry Bases/Jin A Wicker Beast',
    'Avatars/Furry Bases/Jin A Griffin',
    'Avatars/Furry Bases/Jin A Lux Deluxe',
    'Avatars/Furry Bases/Jin A Insect Kaiju',
    'Avatars/Furry Bases/Jin A Ampwave',
    'Avatars/Furry Bases/Jin A Kahruga Kaiju',
    'Avatars/Furry Bases/Nardo Nardo Dragon',
    'Avatars/Furry Bases/Hobbert Hobkin',
    'Avatars/Furry Bases/Hobbert Aqualux',
    'Avatars/Furry Bases/Hobbert Hobkin Redux',
    'Avatars/Furry Bases/Hobbert Necronynx',
    'Avatars/Furry Bases/Hobbert Mewlin',
    'Avatars/Furry Bases/Hobbert Arflin',
    'Avatars/Furry Bases/Hobbert Dranari',
    'Avatars/Furry Bases/Hobbert Hobdog',
    'Avatars/Furry Bases/Hobbert Chipori',
    'Avatars/Furry Bases/Nara Narachi',
    'Avatars/Furry Bases/Nicoreda Nicoreda Protogen',
    'Avatars/Furry Bases/Nicoreda Batdal',
    'Avatars/Furry Bases/Nicoreda Kobodal',
    'Avatars/Furry Bases/Alber Hyenid',
    'Avatars/Furry Bases/Alber Coyote',
    'Avatars/Furry Bases/Alber Draconian',
    'Avatars/Furry Bases/Izzy Capricornian',
    'Avatars/Furry Bases/Kalasnokov Alphagen',
    'Avatars/Furry Bases/jzody Grinlin',
    'Avatars/Furry Bases/jzody Impim',
    'Avatars/Furry Bases/jzody Lambda',
    'Avatars/Furry Bases/jzody Oni Impim',
    'Avatars/Furry Bases/Ghostly Female Felines',
    'Avatars/Furry Bases/Ghostly Horses',
    'Avatars/Furry Bases/Ghostly Canines',
    'Avatars/Furry Bases/Ghostly Mama-gen',
    'Avatars/Furry Bases/Mari Maruchi',
    'Avatars/Furry Bases/Mari Deirachi',
    'Avatars/Furry Bases/Mari Akky V2',
    'Avatars/Furry Bases/Mari Carbuncle',
    'Avatars/Furry Bases/Winterpaw Mouse',
    'Avatars/Furry Bases/Winterpaw Cat',
    'Avatars/Furry Bases/Winterpaw Canine',
    'Avatars/Furry Bases/Winterpaw Female Canine',
    'Avatars/Furry Bases/Winterpaw Cheetah',
    'Avatars/Furry Bases/Odo Goldenpaws Avatars Foxxo',
    'Avatars/Furry Bases/Odo Goldenpaws Avatars Pup pack',
    'Avatars/Furry Bases/Nukude NKD Protogen',
    'Avatars/Furry Bases/Nukude Moomba',
    'Avatars/Furry Bases/Nukude Wisper',
    'Avatars/Furry Bases/Nukude Lufare',
    'Avatars/Furry Bases/Nukude Nukvali',
    'Avatars/Furry Bases/Javenchi Javali',
    'Avatars/Furry Bases/Javenchi Leggy Worm',
    'Avatars/Furry Bases/Javenchi Beaky Baedyr',
    'Avatars/Furry Bases/Javenchi Javes',
    'Avatars/Furry Bases/HaruMaki Kirin',
    'Avatars/Furry Bases/HaruMaki ENA',
    'Avatars/Furry Bases/HaruMaki Haru Manokit',
    'Avatars/Furry Bases/HaruMaki Susie',
    'Avatars/Furry Bases/kyderra Floaxy',
    'Avatars/Furry Bases/kyderra Digiguil',
    'Avatars/Furry Bases/Krample sergal',
    'Avatars/Furry Bases/Krample Snaggletooth',
    'Avatars/Furry Bases/Krample Hymir Hound',
    'Avatars/Furry Bases/Shade the Bat Awter',
    'Avatars/Furry Bases/Povi Povichi V1',
    'Avatars/Furry Bases/Povi Povichi V2',
    'Avatars/Furry Bases/Povi Povichi V3',
    'Avatars/Furry Bases/Ikeiwa Lambie',
    'Avatars/Furry Bases/Ikeiwa Lambie 2.0',
    'Avatars/Furry Bases/GamblerPlay Rawrgon',
    'Avatars/Furry Bases/rosebur Aerogen',
    'Avatars/Furry Bases/rosebur Rosavali',
    'Avatars/Furry Bases/rosebur Silvalux',
    'Avatars/Furry Bases/Weasel Gear FoxBox',
    'Avatars/Furry Bases/Hirozu Finzu',
    'Avatars/Furry Bases/Hirozu Zucrose',
    'Avatars/Furry Bases/Hirozu Zuprano',
    'Avatars/Furry Bases/Ghostt Belai',
    'Avatars/Furry Bases/Ghostt Parasite',
    'Avatars/Furry Bases/Ghostt Koru',
    'Avatars/Furry Bases/StarMax Seeker Avali',
    'Avatars/Furry Bases/Wuffwick Zorrix',
    'Avatars/Furry Bases/Wuffwick Neon Wuff',
    'Avatars/Furry Bases/R3D Inc. Talia',
    'Avatars/Furry Bases/R3D Inc. T Bridget',
    'Avatars/Furry Bases/R3D Inc. Rosie',
    'Avatars/Furry Bases/Lune Glaceon',
    'Avatars/Furry Bases/Lune Sylveon',
    'Avatars/Furry Bases/Lune Ankha',
    'Avatars/Furry Bases/Erich Westhoven Kryphus',
    'Avatars/Furry Bases/Erich Westhoven Fenchi',
    'Avatars/Furry Bases/Erich Westhoven Cirvulp',
    'Avatars/Furry Bases/Skibbles Pando',
    'Avatars/Furry Bases/Skibbles Red Panda',
    'Avatars/Furry Bases/Mackenzie Playermodel',
    'Avatars/Furry Bases/GELL Alira',
    'Avatars/Furry Bases/GELL Mei',
    'Avatars/Furry Bases/FrostKittyPaw Canidae',
    'Avatars/Furry Bases/FrostKittyPaw Catbot',
    'Avatars/Furry Bases/FrostKittyPaw Cats',
    'Avatars/Furry Bases/VR_Ris Chameleon',
    'Avatars/Furry Bases/VR_Ris Color dino',
    'Avatars/Furry Bases/VR_Ris Color dino v2',
    'Avatars/Furry Bases/Nessa Lunette',
    'Avatars/Furry Bases/Nessa Kolfur',
    'Avatars/Furry Bases/Nessa Cat',
    'Avatars/Furry Bases/Nessa Vix',
    'Avatars/Furry Bases/Nessa Kara',
    'Avatars/Furry Bases/Joshua Bounds I-MP',
    'Avatars/Furry Bases/Joshua Bounds SUCUB-S',
    'Avatars/Furry Bases/Bartchi Tigrou',
    'Avatars/Furry Bases/Bartchi Hyena',
    'Avatars/Furry Bases/Zarphus Gryphon',
    'Avatars/Furry Bases/Maya-Ayanea Sa-Mi',
    'Avatars/Furry Bases/Maya-Ayanea Asahi',
    'Avatars/Furry Bases/Maya-Ayanea Skullsu',
    'Avatars/Furry Bases/Maya-Ayanea Zetsu',
    'Avatars/Furry Bases/Maya-Ayanea Jim',
    'Avatars/Furry Bases/vr_zab Moth',
    'Avatars/Furry Bases/vr_zab Sheep',
    'Avatars/Furry Bases/vr_zab Raptor',
    'Avatars/Furry Bases/vr_zab Gecko',
    'Avatars/Furry Bases/vr_zab Skunk',
    'Avatars/Furry Bases/vr_zab Skulldog',
    'Avatars/Furry Bases/vr_zab Bird',
    'Avatars/Furry Bases/vr_zab Synth',
    'Avatars/Furry Bases/vr_zab Fennec',
    'Avatars/Furry Bases/vr_zab Bats',
    'Avatars/Furry Bases/vr_zab Otters',
    'Avatars/Furry Bases/vr_zab ProtoGen',
    'Avatars/Furry Bases/vr_zab Manokits',
    'Avatars/Furry Bases/vr_zab Wolves',
    'Avatars/Furry Bases/vr_zab Deer',
    'Avatars/Furry Bases/vr_zab Wickerbeast',
    'Avatars/Furry Bases/vr_zab Dragon',
    'Avatars/Furry Bases/vr_zab Polecat',
    'Avatars/Furry Bases/vr_zab Roo',
    'Avatars/Furry Bases/vr_zab Cruxes',
    'Avatars/Furry Bases/vr_zab Foxes',
    'Avatars/Furry Bases/Tosca Draconis',
    'Avatars/Furry Bases/Tosca Fennixs',
    'Avatars/Furry Bases/Tosca Squeaker',
    'Avatars/Furry Bases/Tosca Vernids',
    'Avatars/Furry Bases/Tosca Rexionium evolved',
    'Avatars/Furry Bases/Tosca Catto',
    'Avatars/Furry Bases/Tosca Pupper',
    'Avatars/Furry Bases/Tosca Kyragan',
    'Avatars/Furry Bases/Tosca Felisian',
    'Avatars/Furry Bases/FreeFox Phoebe Zig',
    'Avatars/Furry Bases/Nessa kolfur',
    'Avatars/Furry Bases/Nessa cat',
    'Avatars/Furry Bases/Nessa Lunette',
    'Avatars/Furry Bases/Nessa Vix',
    'Avatars/Furry Bases/Nessa Kara',
    'Avatars/Furry Bases/Shiba',
    'Avatars/Furry Bases/Drakoob',
    'Avatars/Furry Bases/Nekoob',
    'Avatars/Furry Bases/Fosnero',
    'Avatars/Furry Bases/Estefanoida Seedrian',
    'Avatars/Furry Bases/Estefanoida MewMei Kitty',
    'Avatars/Furry Bases/Estefanoida Shrud',
    'Avatars/Furry Bases/Estefanoida Sceptile',
    'Avatars/Furry Bases/Bestboi Classic',
    'Avatars/Furry Bases/Bestboi HD',
    'Avatars/Furry Bases/Bestboi Dutch Angel',
    'Avatars/Furry Bases/Bestboi Chibi',
    'Avatars/Furry Bases/Bestboi Toon',
    'Avatars/Furry Bases/Regulus',
    'Avatars/Furry Bases/Wuldarren',
    'Avatars/Furry Bases/Silent Dreams Ruby',
    'Avatars/Furry Bases/Silent Dreams Kessa',
    'Avatars/Furry Bases/Silent Dreams Opera',
    'Avatars/Furry Bases/Silent Dreams Magillanica',
    'Avatars/Furry Bases/Silent Dreams Zero',
    'Avatars/Furry Bases/Silent Dreams Yossi & Eerie',
    'Avatars/Furry Bases/Hirozu Zucrose',
    'Avatars/Furry Bases/Hirozu Finzu',
    'Avatars/Furry Bases/Hirozu Zuprano',
    'Avatars/Furry Bases/Zawoo Rascal Rabbit',
    'Avatars/Furry Bases/Zawoo Daring Deer',
    'Avatars/Furry Bases/Zawoo Chaos Canine',
    'Avatars/Furry Bases/Fawnis',
    'Avatars/Furry Bases/Waggan',
    'Avatars/Furry Bases/Skip4d Airplane Dragon',
    'Avatars/Furry Bases/Skip4d Puppy',
    'Avatars/Furry Bases/Skip4d Sea Otter',
    'Avatars/Furry Bases/Skip4d Werewolf',
    'Avatars/Furry Bases/Skip4d Possems & Rodents',
    'Avatars/Furry Bases/Skip4d Big Cats',
    'Avatars/Furry Bases/Fluffsel',
    'Avatars/Furry Bases/Oken Bunny',
    'Avatars/Furry Bases/Oken Fennec',
    'Avatars/Furry Bases/Oken Kuriko',
    'Avatars/Furry Bases/Oken Horse',
    'Avatars/Furry Bases/Oken Dragon',
    'Avatars/Furry Bases/Spiffy Foxy Mouse',
    'Avatars/Furry Bases/Spiffy Daisy',
    'Avatars/Furry Bases/Natch Deux Aki',
    'Avatars/Furry Bases/Natch Deux Kina',
    'Avatars/Furry Bases/Natch Deux Vix',
    'Avatars/Furry Bases/Natch Deux Nago',
    'Avatars/Furry Bases/Natch Deux Nuwa',
    'Avatars/Furry Bases/Natch Deux Clover',
    'Avatars/Furry Bases/Natch Deux Salazek Male',
    'Avatars/Furry Bases/Natch Deux Salazek Female',
    'Avatars/Furry Bases/Allbadbadgers Zoroark',
    'Avatars/Furry Bases/Allbadbadgers Goodra',
    'Avatars/Furry Bases/Allbadbadgers Sentry',
    'Avatars/Furry Bases/Allbadbadgers Mewtwo',
    'Avatars/Furry Bases/Allbadbadgers Lucario',
    'Avatars/Furry Bases/LCD Plushby',
    'Avatars/Furry Bases/LCD ViskaHound',
    'Avatars/Furry Bases/LCD Beaninies',
    'Avatars/Furry Bases/LCD Anteater'
    'Avatars/Furry Bases/Space Birb Keiko Kitty',
    'Avatars/Furry Bases/Space Birb Snake Friend',
    'Avatars/Furry Bases/Space Birb Aquabeast',
    'Avatars/Furry Bases/Space Birb Owl',
    'Avatars/Furry Bases/Rice Baller kitty',
    'Avatars/Furry Bases/Rice Floffy Kitty',
    'Avatars/Furry Bases/Spaghet VRaptor',
    'Avatars/Furry Bases/Spaghet Leggy',
    'Avatars/Furry Bases/Spaghet Deer',
    'Avatars/Furry Bases/Spaghet Kangaroo',
    'Avatars/Furry Bases/Spaghet Fox',
    'Avatars/Furry Bases/Spaghet Crux',
    'Avatars/Furry Bases/Ghost Cabbit Panderp',
    'Avatars/Furry Bases/Ghost Cabbit Fluffer',
    'Avatars/Furry Bases/JustDamen Lynx',
    'Avatars/Furry Bases/Rai Kitamatsu Kitadragon',
    'Avatars/Furry Bases/Rai Kitamatsu Kitabunny',
    'Avatars/Furry Bases/Rai Kitamatsu Jerry Avali',
    'Avatars/Furry Bases/Caboose Kibi',
    'Avatars/Furry Bases/Caboose Aether',
    'Avatars/Furry Bases/Vulthra Pooltoy',
    'Avatars/Furry Bases/Vulthra Zipper',
    'Avatars/Furry Bases/Vulthra Chonky Chicken',
    'Avatars/Furry Bases/Vulthra Sheepy sheep',
    'Avatars/Furry Bases/Lexidoll Renamon',
    'Avatars/Furry Bases/Lexidoll Lexichi',
    'Avatars/Furry Bases/Lexidoll Latex Demon',
    'Avatars/Furry Bases/Lexidoll Robbunni',
    'Avatars/Furry Bases/Lexidoll LexiDemon',
    'Avatars/Furry Bases/Skully Hellfire Chimera',
    'Avatars/Furry Bases/Skully Hellfire ARIA_MK_1',
    'Avatars/Furry Bases/Skully Hellfire Bone Wraith',
    'Avatars/Furry Bases/Skully Hellfire Murdoc',
    'Avatars/Furry Bases/Skully Hellfire Beezle',
    'Avatars/Furry Bases/Skye Otter',
    'Avatars/Furry Bases/Skye Taryk',
    'Avatars/Furry Bases/Skye Terris',
    'Avatars/Furry Bases/Skye Tiger',
    'Avatars/Furry Bases/Skye Orca',
    'Avatars/Furry Bases/Skye Sky',
    'Avatars/Furry Bases/Skye Rabbit',
    'Avatars/Furry Bases/Spade Derg',
    'Avatars/Furry Bases/Spade Fennec',
    'Avatars/Furry Bases/Leedro Kats',
    'Avatars/Furry Bases/JforrestE Fennec',
    'Avatars/Furry Bases/JforrestE Fey',
    'Avatars/Furry Bases/JforrestE Wuldarren',
    'Avatars/Furry Bases/Yersinia Pestis Mothmello',
    'Avatars/Furry Bases/Yersinia Pestis Protogen',
    'Avatars/Furry Bases/Yersinia Pestis Frilled Lizard',
    'Avatars/Furry Bases/Cinners Bnuuy Bunny',
    'Avatars/Furry Bases/Aegeus Blackmane Badger',
    'Avatars/Furry Bases/Aegeus Blackmane Horse',
    'Avatars/Furry Bases/Coyotic Trouble Canine',
    'Avatars/Furry Bases/Coyotic Trouble Fox',
    'Avatars/Furry Bases/Coyotic Trouble Quadruped Canine',
    'Avatars/Furry Bases/Emperor of Mars Squirrel',
    'Avatars/Furry Bases/Emperor of Mars Squirox',
    'Avatars/Furry Bases/LokeToki Drax',
    'Avatars/Furry Bases/Neop Bat',
    'Avatars/Furry Bases/Neop Kobold',
    'Avatars/Furry Bases/RADICALnorm Hound',
    'Avatars/Furry Bases/RADICALnorm Foxbody',
    'Avatars/Furry Bases/RADICALnorm Mini Dragon',
    'Avatars/Furry Bases/RADICALnorm SOMA',
    'Avatars/Furry Bases/Nindo Geckbold',
    'Avatars/Furry Bases/Nindo Gallosaur',
    'Avatars/Furry Bases/Nindo Doogle',
    'Avatars/Furry Bases/Dvorakir Dezil',
    'Avatars/Furry Bases/Dvorakir Possila',
    'Avatars/Furry Bases/Dvorakir Shiron',
    'Avatars/Furry Bases/Dvorakir Skafu',
    'Avatars/Furry Bases/Dvorakir Lugia',
    'Avatars/Furry Bases/Dvorakir Nezzucho',
    'Avatars/Furry Bases/Dvorakir Kyra',
    'Avatars/Furry Bases/Gillboy Merinian',
    'Avatars/Furry Bases/Lux Aeterna Zumas',
    'Avatars/Furry Bases/Lux Aeterna Protogen',
    'Avatars/Furry Bases/Lux Aeterna Rabbizorg',
    'Avatars/Furry Bases/Lux Aeterna Mantled',
    'Avatars/Furry Bases/Lux Aeterna Synth Sobek',
    'Avatars/Furry Bases/Lux Aeterna Synth Female',
    'Avatars/Furry Bases/Lux Aeterna Synth Worker',
    'Avatars/Furry Bases/Lux Aeterna Synth Male',
    'Avatars/Furry Bases/Laionss Tiger',
    'Avatars/Furry Bases/Laionss Wolf',
    'Avatars/Furry Bases/Shiapra Birdie',
    'Avatars/Furry Bases/Shiapra Lucario',
    'Avatars/Furry Bases/Reval Fox',
    'Avatars/Furry Bases/Tokyozilla Dragon',
    'Avatars/Furry Bases/Tokyozilla Biridios',
    'Avatars/Furry Bases/Tokyozilla Kaiju',
    'Avatars/Furry Bases/Tokyozilla Carnosaur',
    'Avatars/Furry Bases/Tokyozilla Tiger Bee',
    'Avatars/Furry Bases/ZinPia Zeedah'
]

Premade_Avatars = [
    'Avatars/Premade/Bratbun Locke',
    'Avatars/Premade/Bratbun Jinx',
    'Avatars/Premade/Bratbun Viktor',
    'Avatars/Premade/Bratbun Hexa',
    'Avatars/Premade/Bratbun Candi',
    'Avatars/Premade/Bratbun Roxie',
    'Avatars/Premade/Bratbun Amara',
    'Avatars/Premade/Bratbun Seth',
    'Avatars/Premade/Bratbun Ivy',
    'Avatars/Premade/Bratbun Zoe',
    'Avatars/Premade/Bratbun Jay',
    'Avatars/Premade/Bratbun Salem',
    'Avatars/Premade/Bratbun Sienna',
    'Avatars/Premade/JellyM@gg0tz Ashe',
    'Avatars/Premade/JellyM@gg0tz Jasper',
    'Avatars/Premade/JellyM@gg0tz Moichi',
    'Avatars/Premade/JellyM@gg0tz Blair',
    'Avatars/Premade/JellyM@gg0tz Socks',
    'Avatars/Premade/Sunny64 Sun and Moon',
    'Avatars/Premade/Sunny64 Kismett',
    'Avatars/Premade/Mari Jacob',
    'Avatars/Premade/Mari Fafnir Bunny',
    'Avatars/Premade/Mari Kuu',
    'Avatars/Premade/Mari Fafnir Tiger',
    'Avatars/Premade/From the Graves Little Beau Creep',
    'Avatars/Premade/From the Graves JellyBish',
    'Avatars/Premade/From the Graves Lemon',
    'Avatars/Premade/From the Graves Big Boss Bowsette',
    'Avatars/Premade/From the Graves Queen Bowsette',
    'Avatars/Premade/From the Graves Lil Lime',
    'Avatars/Premade/From the Graves Kusari',
    'Avatars/Premade/From the Graves Red',
    'Avatars/Premade/From the Graves Chaos',
    'Avatars/Premade/From the Graves Cherry',
    'Avatars/Premade/From the Graves Oracle',
    'Avatars/Premade/DreamyNomu Celeste',
    'Avatars/Premade/DreamyNomu Shroomie',
    'Avatars/Premade/DreamyNomu Usagi',
    'Avatars/Premade/DreamyNomu Kit-Kat',
    'Avatars/Premade/DreamyNomu Cupid',
    'Avatars/Premade/DreamyNomu Kitsune',
    'Avatars/Premade/DreamyNomu Mousie',
    'Avatars/Premade/DreamyNomu Sprout',
    'Avatars/Premade/DreamyNomu Crescent',
    'Avatars/Premade/Cams Avis Remi',
    'Avatars/Premade/Cams Avis Hari',
    'Avatars/Premade/Cams Avis Sophie',
    'Avatars/Premade/Cams Avis Jamie',
    'Avatars/Premade/Meechu Critical',
    'Avatars/Premade/Meechu Berserk',
    'Avatars/Premade/Meechu Kyo',
    'Avatars/Premade/Meechu Datenshi',
    'Avatars/Premade/Meechu Pain',
    'Avatars/Premade/-ReFleX- Silent',
    'Avatars/Premade/-ReFleX- Graffiti',
    'Avatars/Premade/-ReFleX- 3k',
    'Avatars/Premade/-ReFleX- Blue Bomber',
    'Avatars/Premade/Googis Avatars Ash',
    'Avatars/Premade/Googis Avatars Nagato',
    'Avatars/Premade/Googis Avatars Chloe',
    'Avatars/Premade/Googis Avatars Natalie',
    'Avatars/Premade/CuteBunny Motchi',
    'Avatars/Premade/CuteBunny Missky',
    'Avatars/Premade/CuteBunny Oshita',
    'Avatars/Premade/CuteBunny Burona',
    'Avatars/Premade/CuteBunny Anubis',
    'Avatars/Premade/CuteBunny Baste',
    'Avatars/Premade/CuteBunny Kira',
    'Avatars/Premade/CuteBunny Hard candy',
    'Avatars/Premade/CuteBunny Rea & Otix',
    'Avatars/Premade/Larens Hime',
    'Avatars/Premade/Larens Yana',
    'Avatars/Premade/Larens Kain',
    'Avatars/Premade/Larens Malaya',
    'Avatars/Premade/Larens Ciry',
    'Avatars/Premade/Iridescence Luna',
    'Avatars/Premade/Iridescence Valkyrie',
    'Avatars/Premade/Iridescence Jackel',
    'Avatars/Premade/Iridescence Aegis',
    'Avatars/Premade/Iridescence Kuro',
    'Avatars/Premade/Iridescence Ghxst',
    'Avatars/Premade/Naiii Yuuri',
    'Avatars/Premade/Naiii Mooli',
    'Avatars/Premade/Naiii Booni',
    'Avatars/Premade/Nawty Nawtisen',
    'Avatars/Premade/Nawty Nawtesy',
    'Avatars/Premade/Nawty Nwatily',
    'Avatars/Premade/CastellVR Nina',
    'Avatars/Premade/CastellVR Demoness',
    'Avatars/Premade/CastellVR Qiuyue',
    'Avatars/Premade/Lucas369 Blaze',
    'Avatars/Premade/Lucas369 Rosaline',
    'Avatars/Premade/Lucas369 Ellie',
    'Avatars/Premade/Lucas369 Nena',
    'Avatars/Premade/Lucas369 Tony',
    'Avatars/Premade/Lucas369 Damien',
    'Avatars/Premade/Lucas369 Octavia',
    'Avatars/Premade/Lucas369 Ray',
    'Avatars/Premade/Lucas369 Prancer',
    'Avatars/Premade/New Eden Interactive Columbia',
    'Avatars/Premade/New Eden Interactive Bunny',
    'Avatars/Premade/New Eden Interactive Bat',
    'Avatars/Premade/New Eden Interactive Lun',
    'Avatars/Premade/New Eden Interactive Sol',
    'Avatars/Premade/New Eden Interactive Lilith',
    'Avatars/Premade/New Eden Interactive Gate',
    'Avatars/Premade/New Eden Interactive Key',
    'Avatars/Premade/★彡 Wraith',
    'Avatars/Premade/★彡 Bones',
    'Avatars/Premade/★彡 Hellcat',
    'Avatars/Premade/★彡 Rotten',
    'Avatars/Premade/★彡 Gaslight',
    'Avatars/Premade/★彡 Burden',
    'Avatars/Premade/★彡 Another',
    'Avatars/Premade/★彡 Agony',
    'Avatars/Premade/★彡 Dust',
    'Avatars/Premade/A k i r a Vizion',
    'Avatars/Premade/A k i r a Ronin',
    'Avatars/Premade/A k i r a Zero',
    'Avatars/Premade/A k i r a Jade',
    'Avatars/Premade/A k i r a Khaido',
    'Avatars/Premade/A k i r a Khydea',
    'Avatars/Premade/Cozu Tora',
    'Avatars/Premade/Cozu Taiga',
    'Avatars/Premade/Griffonka Lilith',
    'Avatars/Premade/Griffonka Panter',
    'Avatars/Premade/Griffonka Pantera',
    'Avatars/Premade/Griffonka Strawberry',
    'Avatars/Premade/Griffonka Ryoko',
    'Avatars/Premade/Griffonka Night',
    'Avatars/Premade/Griffonka Cearful',
    'Avatars/Premade/Griffonka Reckless',
    'Avatars/Premade/Griffonka Eden',
    'Avatars/Premade/Griffonka Andromeda',
    'Avatars/Premade/Griffonka Calypso',
    'Avatars/Premade/Griffonka Pennelope',
    'Avatars/Premade/Griffonka Bambi',
    'Avatars/Premade/Griffonka Wolf',
    'Avatars/Premade/Griffonka Nala',
    'Avatars/Premade/Griffonka Prime',
    'Avatars/Premade/Griffonka Freyia',
    'Avatars/Premade/Griffonka Blaze',
    'Avatars/Premade/Griffonka Light',
    'Avatars/Premade/Griffonka Zack',
    'Avatars/Premade/Griffonka Zoey',
    'Avatars/Premade/Griffonka Drags',
    'Avatars/Premade/Griffonka Dragonis',
    'Avatars/Premade/Griffonka Wraith',
    'Avatars/Premade/Griffonka Ghost',
    'Avatars/Premade/Griffonka Banish',
    'Avatars/Premade/Griffonka Hanzo',
    'Avatars/Premade/Griffonka Crystal',
    'Avatars/Premade/Griffonka Snow',
    'Avatars/Premade/Griffonka Mantus',
    'Avatars/Premade/Griffonka Mania',
    'Avatars/Premade/Griffonka Sinner',
    'Avatars/Premade/Griffonka Villain',
    'Avatars/Premade/Griffonka Demon Huntress',
    'Avatars/Premade/Cheese Store Ote',
    'Avatars/Premade/Cheese Store Park',
    'Avatars/Premade/Cheese Store Sea',
    'Avatars/Premade/Cheese Store Jimin',
    'Avatars/Premade/falsk Lucas',
    'Avatars/Premade/falsk Nine',
    'Avatars/Premade/falsk Rain',
    'Avatars/Premade/falsk Alex',
    'Avatars/Premade/falsk Leo',
    'Avatars/Premade/falsk Sam',
    'Avatars/Premade/Kyanite Lynx',
    'Avatars/Premade/Kyanite Blinx',
    'Avatars/Premade/Kyanite Xena',
    'Avatars/Premade/Kyanite Suki',
    'Avatars/Premade/Kyanite Aria',
    'Avatars/Premade/Kyanite Candy',
    'Avatars/Premade/Kyanite Viper',
    'Avatars/Premade/Kyanite Yume',
    'Avatars/Premade/Kyanite Ryoko',
    'Avatars/Premade/Kyanite Jay',
    'Avatars/Premade/Kyanite Jen',
    'Avatars/Premade/Kyanite Kei',
    'Avatars/Premade/Kyanite Emiko',
    'Avatars/Premade/Kyanite Lia',
    'Avatars/Premade/Kyanite Jade',
    'Avatars/Premade/Kyanite Natsu',
    'Avatars/Premade/Kyanite Rin',
    'Avatars/Premade/Kyanite Blossom',
    'Avatars/Premade/Kyanite Anne',
    'Avatars/Premade/Kyanite Hinata',
    'Avatars/Premade/Kyanite Dawn',
    'Avatars/Premade/Kyanite Dusk',
    'Avatars/Premade/Kyanite Donut',
    'Avatars/Premade/Kyanite Yuzu',
    'Avatars/Premade/Kyanite Haku',
    'Avatars/Premade/Elenas Shop Pasuteru',
    'Avatars/Premade/Elenas Shop Senshi',
    'Avatars/Premade/Elenas Shop Niso',
    'Avatars/Premade/Elenas Shop Kuma',
    'Avatars/Premade/Elenas Shop Koumori',
    'Avatars/Premade/Elenas Shop Moira',
    'Avatars/Premade/Elenas Shop Amai',
    'Avatars/Premade/Elenas Shop HWAA Male',
    'Avatars/Premade/Elenas Shop HWAA Female',
    'Avatars/Premade/Elenas Shop Joyful Kiss',
    'Avatars/Premade/Elenas Shop Maniac',
    'Avatars/Premade/Elenas Shop Sophie',
    'Avatars/Premade/Elenas Shop Colorful Crush',
    'Avatars/Premade/Elenas Shop Eve',
    'Avatars/Premade/Elenas Shop Tako',
    'Avatars/Premade/Elenas Shop Crybaby',
    'Avatars/Premade/Elenas Shop Valentine',
    'Avatars/Premade/Elenas Shop Aria',
    'Avatars/Premade/Elenas Shop Shitsuren',
    'Avatars/Premade/Elenas Shop XII',
    'Avatars/Premade/Elenas Shop Awai Tsuki',
    'Avatars/Premade/Elenas Shop VI',
    'Avatars/Premade/Elenas Shop Ace',
    'Avatars/Premade/Elenas Shop Shika',
    'Avatars/Premade/Elenas Shop Koneko',
    'Avatars/Premade/Elenas Shop Majo',
    'Avatars/Premade/Elenas Shop Tenma Female',
    'Avatars/Premade/Elenas Shop Tenma Male',
    'Avatars/Premade/Elenas Shop Succubus Muma',
    'Avatars/Premade/Elenas Shop Fena',
    'Avatars/Premade/Elenas Shop Ushi',
    'Avatars/Premade/Elenas Shop Ana',
    'Avatars/Premade/Elenas Shop Valeria',
    'Avatars/Premade/Elenas Shop Vivy',
    'Avatars/Premade/Elenas Shop Momo',
    'Avatars/Premade/Elenas Shop Kei',
    'Avatars/Premade/Elenas Shop Nino',
    'Avatars/Premade/Elenas Shop Riko',
    'Avatars/Premade/Elenas Shop Lisa',
    'Avatars/Premade/Elenas Shop Deva',
    'Avatars/Premade/Elenas Shop Mana',
    'Avatars/Premade/Elenas Shop Kanna',
    'Avatars/Premade/Elenas Shop Asami',
    'Avatars/Premade/Elenas Shop Mika',
    'Avatars/Premade/Elenas Shop Shayla',
    'Avatars/Premade/Elenas Shop Evelyn',
    'Avatars/Premade/Elenas Shop Sherry',
    'Avatars/Premade/Elenas Shop Remi',
    'Avatars/Premade/Elenas Shop Maladie',
    'Avatars/Premade/Elenas Shop Hina',
    'Avatars/Premade/Elenas Shop Estelle',
    'Avatars/Premade/Elenas Shop Mola',
    'Avatars/Premade/Elenas Shop Tiana',
    'Avatars/Premade/Elenas Shop Philia',
    'Avatars/Premade/Elenas Shop Tiffany',
    'Avatars/Premade/Elenas Shop Celia',
    'Avatars/Premade/Elenas Shop Sweetbunn',
    'Avatars/Premade/Elenas Shop Roxxy',
    'Avatars/Premade/Elenas Shop Maple',
    'Avatars/Premade/Elenas Shop Candice',
    'Avatars/Premade/друг Varine',
    'Avatars/Premade/друг Algorithm',
    'Avatars/Premade/друг Keva',
    'Avatars/Premade/друг Noelle',
    'Avatars/Premade/друг Fae',
    'Avatars/Premade/друг Bonbon',
    'Avatars/Premade/друг Chammy',
    'Avatars/Premade/друг Booniez Bagz',
    'Avatars/Premade/друг Bond',
    'Avatars/Premade/друг Mary',
    'Avatars/Premade/SageSpicy Roxie',
    'Avatars/Premade/SageSpicy Asami',
    'Avatars/Premade/SageSpicy Roselyn',
    'Avatars/Premade/SageSpicy Juju',
    'Avatars/Premade/SageSpicy Daisey',
    'Avatars/Premade/SageSpicy Nebula',
    'Avatars/Premade/SageSpicy Pandora',
    'Avatars/Premade/SageSpicy Rheanys',
    'Avatars/Premade/Sam Teddy',
    'Avatars/Premade/Sam Blake',
    'Avatars/Premade/Sam Bentley',
    'Avatars/Premade/Sam Bella',
    'Avatars/Premade/Sam Akuma',
    'Avatars/Premade/Sam Billie',
    'Avatars/Premade/Team. Sector C Eve',
    'Avatars/Premade/Team. Sector C Black cat',
    'Avatars/Premade/Team. Sector C Cia',
    'Avatars/Premade/Team. Sector C Yu-Ri',
    'Avatars/Premade/Team. Sector C Yong-Soon',
    'Avatars/Premade/Team. Sector C Shana',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Rosie',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Malware',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Zombabe',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Orion',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Marie',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Nova',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Priscilla',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Roxy',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Aurora',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Kale',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Victoria',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Sang-woo',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Connie',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ David',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Regina',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Edward',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Nolan',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ MeloMelo',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ KuroKuro',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Bloom',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Bobble',
    'Avatars/Premade/ꜱᴛʀᴀᴡʙᴜɴɴʏ Discord Baby',
    'Avatars/Premade/Lestery VRC OWT',
    'Avatars/Premade/Lestery VRC Trinity Spirit',
    'Avatars/Premade/Lestery VRC Panda Girl',
    'Avatars/Premade/Lestery VRC Trinity Father',
    'Avatars/Premade/Lestery VRC Trinity Son',
    'Avatars/Premade/Snitchie Botto',
    'Avatars/Premade/Snitchie Kalma',
    'Avatars/Premade/Snitchie Elysium',
    'Avatars/Premade/Snitchie Ezra',
    'Avatars/Premade/Snitchie Kalma',
    'Avatars/Premade/Snitchie Ozul',
    'Avatars/Premade/Snitchie Grim',
    'Avatars/Premade/Snitchie Zeno',
    'Avatars/Premade/Snitchie Saber',
    'Avatars/Premade/Snitchie Scythe',
    'Avatars/Premade/Snitchie Nya',
    'Avatars/Premade/Snitchie Poe',
    'Avatars/Premade/Snitchie Dex',
    'Avatars/Premade/Snitchie Lazarus',
    'Avatars/Premade/Snitchie Lemures',
    'Avatars/Premade/Snitchie Aina',
    'Avatars/Premade/Snitchie Shouko',
    'Avatars/Premade/Snitchie Shoya',
    'Avatars/Premade/Snitchie Iris',
    'Avatars/Premade/Snitchie Never',
    'Avatars/Premade/Snitchie Ever',
    'Avatars/Premade/Snitchie ChibiHate',
    'Avatars/Premade/Snitchie Despise',
    'Avatars/Premade/Kittyz Luciel',
    'Avatars/Premade/Kittyz Lucius',
    'Avatars/Premade/Kittyz Anubis',
    'Avatars/Premade/Kittyz Luna',
    'Avatars/Premade/Kittyz Sensei',
    'Avatars/Premade/Kittyz Tora',
    'Avatars/Premade/Kittyz Noah',
    'Avatars/Premade/Antie Ivar',
    'Avatars/Premade/Antie Elvira',
    'Avatars/Premade/Antie Azreal',
    'Avatars/Premade/Antie Dire',
    'Avatars/Premade/Antie Nix',
    'Avatars/Premade/Ourse Daffodil',
    'Avatars/Premade/Ourse Peeper',
    'Avatars/Premade/Ourse Suki',
    'Avatars/Premade/Ourse Toast',
    'Avatars/Premade/Ourse Sayaka',
    'Avatars/Premade/Ourse Bean',
    'Avatars/Premade/Ourse Sayaka',
    'Avatars/Premade/Julie Lisa',
    'Avatars/Premade/Julie Cecilia',
    'Avatars/Premade/Julie Susan',
    'Avatars/Premade/Julie Jake',
    'Avatars/Premade/Julie Viper',
    'Avatars/Premade/Julie Chris',
    'Avatars/Premade/Julie Yuna',
    'Avatars/Premade/Julie Sora',
    'Avatars/Premade/Julie Lyna',
    'Avatars/Premade/Julie Thyst',
    'Avatars/Premade/Julie Tiny Lulu',
    'Avatars/Premade/ARKHYPE Aristo',
    'Avatars/Premade/ARKHYPE Peon',
    'Avatars/Premade/ARKHYPE Psion',
    'Avatars/Premade/ARKHYPE Deceit',
    'Avatars/Premade/ARKHYPE Blackout',
    'Avatars/Premade/ARKHYPE Conquest',
    'Avatars/Premade/ARKHYPE Warpath',
    'Avatars/Premade/ARKHYPE Enthrall',
    'Avatars/Premade/ARKHYPE Bloom',
    'Avatars/Premade/Zeffyrs Avatars Sasha',
    'Avatars/Premade/Zeffyrs Avatars Azar',
    'Avatars/Premade/Zeffyrs Avatars Ifira',
    'Avatars/Premade/Zeffyrs Avatars Victoria',
    'Avatars/Premade/Zeffyrs Avatars Nayeli',
    'Avatars/Premade/Zeffyrs Avatars Ollie',
    'Avatars/Premade/Zeffyrs Avatars Callie',
    'Avatars/Premade/Zeffyrs Avatars Blue Fox Girl',
    'Avatars/Premade/Zeffyrs Avatars Kara',
    'Avatars/Premade/Zeffyrs Avatars Max',
    'Avatars/Premade/Zeffyrs Avatars Lust',
    'Avatars/Premade/Zeffyrs Avatars Greed',
    'Avatars/Premade/Zeffyrs Avatars Midas',
    'Avatars/Premade/Zeffyrs Avatars Anubis',
    'Avatars/Premade/Zeffyrs Avatars Leo',
    'Avatars/Premade/Zeffyrs Avatars Lucy',
    'Avatars/Premade/Zeffyrs Avatars Toki',
    'Avatars/Premade/Zeffyrs Avatars Pride',
    'Avatars/Premade/Zeffyrs Avatars Moon Goddess',
    'Avatars/Premade/noomui Snapdragon',
    'Avatars/Premade/noomui Hana',
    'Avatars/Premade/noomui Sonya',
    'Avatars/Premade/RedOtter Katsumi',
    'Avatars/Premade/Artist Gallery Codi',
    'Avatars/Premade/Artist Gallery Vail',
    'Avatars/Premade/Artist Gallery Kenji',
    'Avatars/Premade/Artist Gallery Zeke',
    'Avatars/Premade/Artist Gallery Lia',
    'Avatars/Premade/Artist Gallery K-pop Killer',
    'Avatars/Premade/Artist Gallery Gojou',
    'Avatars/Premade/Astrafluff Pepper',
    'Avatars/Premade/Astrafluff Sunny',
    'Avatars/Premade/Renni Ryze',
    'Avatars/Premade/Renni Kronos',
    'Avatars/Premade/Renni Kira',
    'Avatars/Premade/1xin Yoevin',
    'Avatars/Premade/1xin Oaki',
    'Avatars/Premade/1xin Xentrics',
    'Avatars/Premade/1xin Vaal',
    'Avatars/Premade/Virtual Threads Viktor',
    'Avatars/Premade/Virtual Threads Marcus',
    'Avatars/Premade/Virtual Threads Ren',
    'Avatars/Premade/Virtual Threads Nicky',
    'Avatars/Premade/Virtual Threads Vertigo',
    'Avatars/Premade/KrysticCat Jax',
    'Avatars/Premade/KrysticCat Hina',
    'Avatars/Premade/KrysticCat Kate',
    'Avatars/Premade/KrysticCat Lori',
    'Avatars/Premade/juuul Silas',
    'Avatars/Premade/juuul Sweets',
    'Avatars/Premade/juuul Jinny',
    'Avatars/Premade/juuul Matrix',
    'Avatars/Premade/OniiGirii Kitten',
    'Avatars/Premade/OniiGirii Chinatsu',
    'Avatars/Premade/Pursu Alex',
    'Avatars/Premade/Pursu Finn',
    'Avatars/Premade/Pursu Rei',
    'Avatars/Premade/Pursu Nala',
    'Avatars/Premade/Pursu Quinn',
    'Avatars/Premade/Pursu Rachel',
    'Avatars/Premade/Pursu Senko',
    'Avatars/Premade/Pursu Sky',
    'Avatars/Premade/Pursu Nightlife',
    'Avatars/Premade/Ritual Zenebra',
    'Avatars/Premade/Ritual Chain',
    'Avatars/Premade/Ritual Chiyo',
    'Avatars/Premade/Remis Avatars Plague Doctor',
    'Avatars/Premade/Remis Avatars Sasha',
    'Avatars/Premade/Remis Avatars Ren',
    'Avatars/Premade/Remis Avatars Wrath',
    'Avatars/Premade/Remis Avatars Vex',
    'Avatars/Premade/Remis Avatars Vi',
    'Avatars/Premade/Remis Avatars Shadow',
    'Avatars/Premade/Remis Avatars Reaper',
    'Avatars/Premade/Remis Avatars Nick',
    'Avatars/Premade/Rynn Melody',
    'Avatars/Premade/Rynn Julie',
    'Avatars/Premade/Rynn Sayuri',
    'Avatars/Premade/Rynn Eira',
    'Avatars/Premade/Rynn Zoe',
    'Avatars/Premade/Rynn Eliza',
    'Avatars/Premade/Rynn Paris',
    'Avatars/Premade/Rynn Luna',
    'Avatars/Premade/Bl4cky Chloe',
    'Avatars/Premade/Bl4cky Violet',
    'Avatars/Premade/Bl4cky Kiara',
    'Avatars/Premade/Bl4cky Yuniko',
    'Avatars/Premade/Bl4cky Sierra',
    'Avatars/Premade/Cryptid Wilbur Milo',
    'Avatars/Premade/Cryptid Wilbur Bat Boy',
    'Avatars/Premade/Cryptid Wilbur Meredith',
    'Avatars/Premade/Cryptid Wilbur Wilbur',
    'Avatars/Premade/Sukawonton Sage',
    'Avatars/Premade/Sukawonton Naomi',
    'Avatars/Premade/Sukawonton Edith',
    'Avatars/Premade/Sukawonton Canine Maruchi',
    'Avatars/Premade/Sukawonton Inky',
    'Avatars/Premade/Xohu and Void Mocha',
    'Avatars/Premade/Xohu and Void Vennox',
    'Avatars/Premade/Xohu and Void Molly',
    'Avatars/Premade/Xohu and Void Elona',
    'Avatars/Premade/Xohu and Void Lucia',
    'Avatars/Premade/Xohu and Void Alani',
    'Avatars/Premade/Xohu and Void Demi',
    'Avatars/Premade/Xohu and Void Haze',
    'Avatars/Premade/Xohu and Void Khloe',
    'Avatars/Premade/OMZ Sniper',
    'Avatars/Premade/OMZ Zesstra',
    'Avatars/Premade/OMZ Rina',
    'Avatars/Premade/OMZ Astrix',
    'Avatars/Premade/OMZ Sobek',
    'Avatars/Premade/OMZ Onzia',
    'Avatars/Premade/zepwlert Shapeshifter',
    'Avatars/Premade/zepwlert Firebender',
    'Avatars/Premade/Kaleeb Taylor',
    'Avatars/Premade/Kaleeb Vizion',
    'Avatars/Premade/Kaleeb Skarlet',
    'Avatars/Premade/Kaleeb Teagan',
    'Avatars/Premade/Xero Ramona',
    'Avatars/Premade/Xero Mey-Rin',
    'Avatars/Premade/Xero Somber',
    'Avatars/Premade/Xero Magic',
    'Avatars/Premade/Xero Raiine',
    'Avatars/Premade/Xero Aly',
    'Avatars/Premade/Xero Scheani',
    'Avatars/Premade/Xero Felix',
    'Avatars/Premade/Starkotic Devine',
    'Avatars/Premade/Starkotic Adore Opti',
    'Avatars/Premade/Starkotic Edith',
    'Avatars/Premade/Starkotic Adore',
    'Avatars/Premade/RaveJesus Sai',
    'Avatars/Premade/RaveJesus Enna',
    'Avatars/Premade/RaveJesus yari',
    'Avatars/Premade/ThePearl Sugari',
    'Avatars/Premade/Zeit Atlas',
    'Avatars/Premade/Zeit Avalon',
    'Avatars/Premade/Confession Knox',
    'Avatars/Premade/Confession Jerico',
    'Avatars/Premade/Confession Rae',
    'Avatars/Premade/Confession Eric',
    'Avatars/Premade/Confession Tyson',
    'Avatars/Premade/Confession Julius',
    'Avatars/Premade/Confession Sylus',
    'Avatars/Premade/Confession Axel',
    'Avatars/Premade/Confession Athena',
    'Avatars/Premade/Dom Darkkie',
    'Avatars/Premade/Dom Oswald',
    'Avatars/Premade/Dom Wolfiyaan',
    'Avatars/Premade/catakitty Sororitas',
    'Avatars/Premade/catakitty Lacey',
    'Avatars/Premade/catakitty Bella',
    'Avatars/Premade/catakitty Beau',
    'Avatars/Premade/catakitty Vira',
    'Avatars/Premade/catakitty Moria',
    'Avatars/Premade/catakitty Ghostly',
    'Avatars/Premade/Wolfs Den 3D Leeah',
    'Avatars/Premade/Wolfs Den 3D Dawn',
    'Avatars/Premade/Wolfs Den 3D Claire',
    'Avatars/Premade/Wolfs Den 3D Sachi',
    'Avatars/Premade/Wolfs Den 3D Chloe',
    'Avatars/Premade/Wolfs Den 3D Ume',
    'Avatars/Premade/Wolfs Den 3D Yuki',
    'Avatars/Premade/Wolfs Den 3D Jade',
    'Avatars/Premade/Wolfs Den 3D Rae',
    'Avatars/Premade/Wolfs Den 3D Alexis',
    'Avatars/Premade/Wolfs Den 3D Azuki-chan',
    'Avatars/Premade/Wolfs Den 3D Cinder',
    'Avatars/Premade/Wolfs Den 3D Alexis',
    'Avatars/Premade/Wolfs Den 3D Sanura',
    'Avatars/Premade/madsters Sitri',
    'Avatars/Premade/madsters Goth Kitty',
    'Avatars/Premade/madsters Ashe',
    'Avatars/Premade/madsters Andri',
    'Avatars/Premade/Simp Over',
    'Avatars/Premade/Simp Elf',
    'Avatars/Premade/Simp Fox',
    'Avatars/Premade/Simp Eboy',
    'Avatars/Premade/Simp Bear',
    'Avatars/Premade/Simp Bubble',
    'Avatars/Premade/Pastnight Shuichi',
    'Avatars/Premade/Pastnight Yokota',
    'Avatars/Premade/Pastnight Mitsou',
    'Avatars/Premade/Pastnight Uzumaki',
    'Avatars/Premade/Pastnight Hisaoka',
    'Avatars/Premade/Pastnight Ryuji',
    'Avatars/Premade/Pastnight Mitsuru',
    'Avatars/Premade/Pastnight Sadako',
    'Avatars/Premade/Pastnight Tomie',
    'Avatars/Premade/Pastnight Kirie',
    'Avatars/Premade/Xelyo Veronica',
    'Avatars/Premade/Xelyo Velse',
    'Avatars/Premade/Xelyo Sophilia',
    'Avatars/Premade/Shevi Luna',
    'Avatars/Premade/Shevi Miyuki',
    'Avatars/Premade/Shevi Asura',
    'Avatars/Premade/Shevi Yuki',
    'Avatars/Premade/Shevi Kruel',
    'Avatars/Premade/Shevi Hori',
    'Avatars/Premade/Shevi Akane',
    'Avatars/Premade/Shevi Setsuko',
    'Avatars/Premade/Shevi Homi',
    'Avatars/Premade/Shevi Kumiko',
    'Avatars/Premade/Shevi Kuro',
    'Avatars/Premade/Shevi Kyui',
    'Avatars/Premade/Shevi Remi',
    'Avatars/Premade/Shevi Ai',
    'Avatars/Premade/Mooky Max',
    'Avatars/Premade/Mooky Kyle',
    'Avatars/Premade/HYEJU Minha',
    'Avatars/Premade/HYEJU Jihyun',
    'Avatars/Premade/HYEJU Yedam',
    'Avatars/Premade/HYEJU Eunju',
    'Avatars/Premade/HYEJU Subin',
    'Avatars/Premade/kri Ani',
    'Avatars/Premade/kri Yui',
    'Avatars/Premade/kri Natalia',
    'Avatars/Premade/kri Viper',
    'Avatars/Premade/NippNipp Cilla',
    'Avatars/Premade/NippNipp Roxie',
    'Avatars/Premade/NippNipp Larken',
    'Avatars/Premade/NippNipp Kaya',
    'Avatars/Premade/NippNipp Octavia',
    'Avatars/Premade/BouncyyUwU Lexii',
    'Avatars/Premade/BouncyyUwU Roxy',
    'Avatars/Premade/BouncyyUwU Melody',
    'Avatars/Premade/BouncyyUwU Sarah',
    'Avatars/Premade/BouncyyUwU FuHua',
    'Avatars/Premade/BouncyyUwU Senna',
    'Avatars/Premade/BouncyyUwU UwUkitty',
    'Avatars/Premade/hiratheemo Mercy',
    'Avatars/Premade/hiratheemo Megan',
    'Avatars/Premade/hiratheemo Chibi Yui',
    'Avatars/Premade/hiratheemo Wolf Bean',
    'Avatars/Premade/hiratheemo Swed',
    'Avatars/Premade/hiratheemo Pumpkin',
    'Avatars/Premade/hiratheemo Vera',
    'Avatars/Premade/hiratheemo Omi',
    'Avatars/Premade/miing Onyx',
    'Avatars/Premade/miing Demi',
    'Avatars/Premade/miing Lily',
    'Avatars/Premade/miing Lacy',
    'Avatars/Premade/miing Vivi',
    'Avatars/Premade/miing Quin',
    'Avatars/Premade/miing Kali',
    'Avatars/Premade/miing Eris',
    'Avatars/Premade/miing Roxy',
    'Avatars/Premade/miing Luna',
    'Avatars/Premade/miing Miya',
    'Avatars/Premade/miing Sua',
    'Avatars/Premade/cow Kaeya',
    'Avatars/Premade/cow Elaine',
    'Avatars/Premade/cow Dai',
    'Avatars/Premade/cow Jane',
    'Avatars/Premade/cow Faye',
    'Avatars/Premade/cow Bun',
    'Avatars/Premade/cow Connie',
    'Avatars/Premade/cow Skyo',
    'Avatars/Premade/cow Nine',
    'Avatars/Premade/cow Dawn',
    'Avatars/Premade/Inku Avenue Aachi',
    'Avatars/Premade/Inku Avenue Cerberus',
    'Avatars/Premade/Inku Avenue Azraelle',
    'Avatars/Premade/Inku Avenue EXI1',
    'Avatars/Premade/Inku Avenue Kira',
    'Avatars/Premade/Inku Avenue Raine',
    'Avatars/Premade/STΔRRΨGΣM Matsumae',
    'Avatars/Premade/STΔRRΨGΣM Beary',
    'Avatars/Premade/STΔRRΨGΣM Scarea',
    'Avatars/Premade/STΔRRΨGΣM Aelia',
    'Avatars/Premade/Trippy Dabi',
    'Avatars/Premade/Trippy Micheal',
    'Avatars/Premade/Trippy Chantele',
    'Avatars/Premade/Trippy Elizabeth',
    'Avatars/Premade/Trippy Travis',
    'Avatars/Premade/Trippy billy',
    'Avatars/Premade/Trippy Dixie',
    'Avatars/Premade/Trippy Vincent',
    'Avatars/Premade/Trippy Felix',
    'Avatars/Premade/Trippy Freya',
    'Avatars/Premade/Trippy Chris',
    'Avatars/Premade/Trippy Demonic Boy',
    'Avatars/Premade/Trippy Demonic Girl',
    'Avatars/Premade/Kirri Cinnamon',
    'Avatars/Premade/Kirri Jenna',
    'Avatars/Premade/Kirri Buttercup',
    'Avatars/Premade/Toast Daisey',
    'Avatars/Premade/Toast River',
    'Avatars/Premade/Toast Syd',
    'Avatars/Premade/Toast Erin',
    'Avatars/Premade/Toast Alyss',
    'Avatars/Premade/Toast Alyxx',
    'Avatars/Premade/Toast Iris',
    'Avatars/Premade/Toast Rinn',
    'Avatars/Premade/Toast Chloe',
    'Avatars/Premade/Toast Finn',
    'Avatars/Premade/Toast Quinn',
    'Avatars/Premade/Toast Angel',
    'Avatars/Premade/Toast Freya',
    'Avatars/Premade/Shizuki Spite',
    'Avatars/Premade/Shizuki Nancy',
    'Avatars/Premade/Shizuki Haiden',
    'Avatars/Premade/Shizuki Aliana',
    'Avatars/Premade/Shizuki Henna',
    'Avatars/Premade/Shizuki Cream Pie',
    'Avatars/Premade/Shizuki Polan',
    'Avatars/Premade/Shizuki Eris',
    'Avatars/Premade/Shizuki Cerys',
    'Avatars/Premade/Shizuki Jaxson',
    'Avatars/Premade/Shizuki Jayla',
    'Avatars/Premade/Shizuki Emmie',
    'Avatars/Premade/Shizuki Willow',
    'Avatars/Premade/Rxsi Angel',
    'Avatars/Premade/Rxsi Devil',
    'Avatars/Premade/Rxsi Sakura',
    'Avatars/Premade/Rxsi Yua',
    'Avatars/Premade/Rxsi Hate',
    'Avatars/Premade/Rxsi Yoru',
    'Avatars/Premade/Rxsi Ai',
    'Avatars/Premade/Rxsi Kyomi',
    'Avatars/Premade/Rxsi Miyu',
    'Avatars/Premade/Rxsi Lena',
    'Avatars/Premade/Rxsi Miruku',
    'Avatars/Premade/Rxsi Kat',
    'Avatars/Premade/Rxsi Kaelie',
    'Avatars/Premade/Rxsi Callisto',
    'Avatars/Premade/Rxsi Acacia',
    'Avatars/Premade/Rxsi Vera',
    'Avatars/Premade/Rxsi Sera',
    'Avatars/Premade/Rxsi Kairi',
    'Avatars/Premade/Rxsi Sadie',
    'Avatars/Premade/Rxsi Mia',
    'Avatars/Premade/KasaiAisu Akame',
    'Avatars/Premade/KasaiAisu Kimiko',
    'Avatars/Premade/KasaiAisu Kouki',
    'Avatars/Premade/KasaiAisu Shani',
    'Avatars/Premade/KasaiAisu Hanami',
    'Avatars/Premade/KasaiAisu Hanako',
    'Avatars/Premade/KasaiAisu Yuka',
    'Avatars/Premade/KasaiAisu Ayumi',
    'Avatars/Premade/KasaiAisu Minami',
    'Avatars/Premade/KasaiAisu Yukine',
    'Avatars/Premade/KasaiAisu Yui',
    'Avatars/Premade/KasaiAisu Nora',
    'Avatars/Premade/KasaiAisu Naomi',
    'Avatars/Premade/KasaiAisu Toxic Girl',
    'Avatars/Premade/KasaiAisu Toxic Boy',
    'Avatars/Premade/Haka Kaizen',
    'Avatars/Premade/Haka Naro',
    'Avatars/Premade/Haka Zin',
    'Avatars/Premade/Haka Monarch',
    'Avatars/Premade/Haka Kyro',
    'Avatars/Premade/Haka Zaya',
    'Avatars/Premade/Haka Free Avatar',
    'Avatars/Premade/ZinPia Dark wolf',
    'Avatars/Premade/Odachi X1',
    'Avatars/Premade/Odachi XO',
    'Avatars/Premade/Odachi Kiri',
    'Avatars/Premade/Odachi Kevi',
    'Avatars/Premade/Odachi Taro',
    'Avatars/Premade/Odachi Goro',
    'Avatars/Premade/Odachi Grace',
    'Avatars/Premade/Odachi Shiro',
    'Avatars/Premade/Odachi Hotaka',
    'Avatars/Premade/Odachi Kouki',
    'Avatars/Premade/Odachi Kyoko',
    'Avatars/Premade/Odachi Asmai',
    'Avatars/Premade/Odachi Yokai',
    'Avatars/Premade/Odachi Tyler',
    'Avatars/Premade/Odachi Tori',
    'Avatars/Premade/Odachi Clay',
    'Avatars/Premade/Odachi Ace',
    'Avatars/Premade/Odachi Finn',
    'Avatars/Premade/Odachi Jack',
    'Avatars/Premade/Odachi Lucas',
    'Avatars/Premade/AcChosen Eimear',
    'Avatars/Premade/AcChosen Psy',
    'Avatars/Premade/AcChosen Atsuko',
    'Avatars/Premade/AcChosen Nadeshiko Kagamihara',
    'Avatars/Premade/soupiee Anya',
    'Avatars/Premade/soupiee Mia',
    'Avatars/Premade/soupiee Amy',
    'Avatars/Premade/soupiee Angel',
    'Avatars/Premade/soupiee Olivia',
    'Avatars/Premade/soupiee Belladonna',
    'Avatars/Premade/soupiee Madison',
    'Avatars/Premade/soupiee Amber',
    'Avatars/Premade/soupiee Ada',
    'Avatars/Premade/soupiee Artemis',
    'Avatars/Premade/soupiee Tulip',
    'Avatars/Premade/soupiee Lily',
    'Avatars/Premade/soupiee Xia',
    'Avatars/Premade/soupiee Ivy',
    'Avatars/Premade/soupiee Denise',
    'Avatars/Premade/soupiee Brianna',
    'Avatars/Premade/soupiee Aurora',
    'Avatars/Premade/soupiee Eliza',
    'Avatars/Premade/soupiee Vesta',
    'Avatars/Premade/soupiee Onyx',
    'Avatars/Premade/soupiee Morgan',
    'Avatars/Premade/soupiee Aphrodite',
    'Avatars/Premade/Battle Bunny Mods Sierra',
    'Avatars/Premade/Battle Bunny Mods R-35 Lbwk',
    'Avatars/Premade/Battle Bunny Mods R-35',
    'Avatars/Premade/Battle Bunny Mods Ivy',
    'Avatars/Premade/Battle Bunny Mods BB Gem',
    'Avatars/Premade/Battle Bunny Mods BB G3',
    'Avatars/Premade/Battle Bunny Mods Rain',
    'Avatars/Premade/Battle Bunny Mods Vega',
    'Avatars/Premade/Battle Bunny Mods Yoco',
    'Avatars/Premade/Battle Bunny Mods Bunny',
    'Avatars/Premade/Battle Bunny Mods Visage',
    'Avatars/Premade/Battle Bunny Mods Trinity',
    'Avatars/Premade/Battle Bunny Mods Mini',
    'Avatars/Premade/Battle Bunny Mods Sentry',
    'Avatars/Premade/Battle Bunny Mods Pilot',
    'Avatars/Premade/Battle Bunny Mods Regalia',
    'Avatars/Premade/Battle Bunny Mods Afterglow',
    'Avatars/Premade/Battle Bunny Mods Amber',
    'Avatars/Premade/Battle Bunny Mods BB',
    'Avatars/Premade/Battle Bunny Mods Sprocket',
    'Avatars/Premade/Battle Bunny Mods Jako',
    'Avatars/Premade/Battle Bunny Mods Kia',
    'Avatars/Premade/Battle Bunny Mods M4X1',
    'Avatars/Premade/Battle Bunny Mods Clara',
    'Avatars/Premade/Battle Bunny Mods Frog',
    'Avatars/Premade/Battle Bunny Mods Mecha Knuck',
    'Avatars/Premade/Battle Bunny Mods G2',
    'Avatars/Premade/CrispTenderloin Buttercup',
    'Avatars/Premade/CrispTenderloin Quinn',
    'Avatars/Premade/Trashy Bean Envy',
    'Avatars/Premade/Trashy Bean Milly',
    'Avatars/Premade/Trashy Bean Mocha',
    'Avatars/Premade/Trashy Bean Elliot',
    'Avatars/Premade/Trashy Bean Ellie',
    'Avatars/Premade/Trashy Bean Sephtis',
    'Avatars/Premade/siren Hellflame',
    'Avatars/Premade/siren Honey',
    'Avatars/Premade/siren Jett',
    'Avatars/Premade/siren Viola',
    'Avatars/Premade/siren Nyx',
    'Avatars/Premade/LozLullaby Chantel',
    'Avatars/Premade/LozLullaby Isla',
    'Avatars/Premade/LozLullaby Aurora',
    'Avatars/Premade/LozLullaby Firefox',
    'Avatars/Premade/LozLullaby Glimmer',
    'Avatars/Premade/LozLullaby Prima',
    'Avatars/Premade/LozLullaby Bandit',
    'Avatars/Premade/LozLullaby Zara',
    'Avatars/Premade/LozLullaby Lovemewolf',
    'Avatars/Premade/LozLullaby Mittens',
    'Avatars/Premade/LozLullaby Nova',
    'Avatars/Premade/LozLullaby Rocket',
    'Avatars/Premade/LozLullaby Inferno',
    'Avatars/Premade/LozLullaby Delilah',
    'Avatars/Premade/LozLullaby Kit',
    'Avatars/Premade/LozLullaby Perri',
    'Avatars/Premade/LozLullaby Kyra',
    'Avatars/Premade/LozLullaby Aphrodite',
    'Avatars/Premade/LozLullaby Aryx',
    'Avatars/Premade/LozLullaby Cupid',
    'Avatars/Premade/LozLullaby Punishmepuppy'
    'Avatars/Premade/LozLullaby Milky',
    'Avatars/Premade/LozLullaby Fae',
    'Avatars/Premade/LozLullaby Cynthia',
    'Avatars/Premade/LozLullaby Assassin',
    'Avatars/Premade/LozLullaby Opus',
    'Avatars/Premade/LozLullaby Feline',
    'Avatars/Premade/Beck Ninomae',
    'Avatars/Premade/Beck Anahi',
    'Avatars/Premade/Beck Asuri',
    'Avatars/Premade/Beck Lex',
    'Avatars/Premade/Beck Blue',
    'Avatars/Premade/Beck Kay',
    'Avatars/Premade/Lolo_VRChat Summer',
    'Avatars/Premade/Lolo_VRChat Alice',
    'Avatars/Premade/Lolo_VRChat Maiko',
    'Avatars/Premade/Lolo_VRChat Valvet',
    'Avatars/Premade/Lolo_VRChat Piper',
    'Avatars/Premade/Lolo_VRChat Koyuki',
    'Avatars/Premade/Lolo_VRChat Yukimi',
    'Avatars/Premade/Miyus Designs Alexis',
    'Avatars/Premade/Miyus Designs Krystal',
    'Avatars/Premade/DerAnwalt Lumi',
    'Avatars/Premade/DerAnwalt Gawr',
    'Avatars/Premade/AlcTrap Selena',
    'Avatars/Premade/AlcTrap Arya',
    'Avatars/Premade/AlcTrap Mira',
    'Avatars/Premade/AlcTrap Sintharia',
    'Avatars/Premade/AlcTrap Sarah',
    'Avatars/Premade/AlcTrap Sade',
    'Avatars/Premade/AlcTrap Aorha',
    'Avatars/Premade/AlcTrap Saphira',
    'Avatars/Premade/AlcTrap Zircon',
    'Avatars/Premade/Minty Chibi',
    'Avatars/Premade/Minty Lisa',
    'Avatars/Premade/Minty Nora',
    'Avatars/Premade/Minty Coco',
    'Avatars/Premade/Minty Abby',
    'Avatars/Premade/Minty Emma',
    'Avatars/Premade/G0RYB0YZVR Jennifer',
    'Avatars/Premade/G0RYB0YZVR Trixie',
    'Avatars/Premade/G0RYB0YZVR Tiffany',
    'Avatars/Premade/Adorapup Mai',
    'Avatars/Premade/Adorapup Rain',
    'Avatars/Premade/Adorapup Magik',
    'Avatars/Premade/Adorapup Erin',
    'Avatars/Premade/Adorapup Lone',
    'Avatars/Premade/Adorapup Castiel',
    'Avatars/Premade/Nyannie Yukki',
    'Avatars/Premade/Nyannie Kami',
    'Avatars/Premade/Nyannie Aoi',
    'Avatars/Premade/skamps Mynx',
    'Avatars/Premade/Phatbroom Mynt',
]

Anime_Avatar_Bases = [
    'Avatars/Anime Bases/Rice Anime Base',
    'Avatars/Anime Bases/Rice Anime Base 2.0',
    'Avatars/Anime Bases/Rice Anime Elf Base',
    'Avatars/Anime Bases/Virturose Female',
    'Avatars/Anime Bases/Virturose Male',
    'Avatars/Anime Bases/ZinPia Zed Base',
    'Avatars/Anime Bases/Battle Bunny Mods Gem Robot Boy',
    'Avatars/Anime Bases/Battle Bunny Mods Gem Robot Girl',
]

Unity_Packages = [
    'Unity Packages/Shaders',
    'Unity Packages/Plugins',
    'Unity Packages/SDKs',
]

Avatar_Addons = [
    'Avatars/Addons/Tails',
    'Avatars/Addons/Ears',
    'Avatars/Addons/Cloths',
    'Avatars/Addons/Textures',
    'Avatars/Addons/Hair',

]